name: northern_trader
description: Northern Trader - Мобильное приложение для торговых каналов
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  country_picker: ^2.0.27
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  uuid: ^4.5.2
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  emoji_picker_flutter: ^2.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  audioplayers: ^6.5.1
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

